In [14]:
print("Jupyter is working in VS Code!")

Jupyter is working in VS Code!


In [15]:
L=[]
for n in range(5):
        L.append(n**2)
        print(L)

[0]
[0, 1]
[0, 1, 4]
[0, 1, 4, 9]
[0, 1, 4, 9, 16]


In [16]:
base_salary=10000
bonus_rate=.10
total_salary=base_salary*(1+bonus_rate)
total_salary

11000.0

In [17]:
type(total_salary)

float

In [18]:
id(total_salary) 
#each variable in Python has a unique id

2491249157008

In [19]:
def introduce_yourself(name, age):
    print(f"Hello, my name is {name}.\nI am {age} years old.")
introduce_yourself("okan", 22)

Hello, my name is okan.
I am 22 years old.


In [20]:
job_title = "Data Scientist"
job_location = "New York"
job_salary = 120000
class Job:
    def __init__(self, title, location, salary):
        self.title = title
        self.location = location
        self.salary = salary
        return print(f"Job Title: {self.title}\nLocation: {self.location}\nSalary: ${self.salary}")
job_1=Job(job_title, job_location, job_salary)
job_1.title

Job Title: Data Scientist
Location: New York
Salary: $120000


'Data Scientist'

In [21]:
help(str)

Help on class str in module builtins:

class str(object)
 |  str(object='') -> str
 |  str(bytes_or_buffer[, encoding[, errors]]) -> str
 |
 |  Create a new string object from the given object. If encoding or
 |  errors is specified, then the object must expose a data buffer
 |  that will be decoded using the given encoding and error handler.
 |  Otherwise, returns the result of object.__str__() (if defined)
 |  or repr(object).
 |  encoding defaults to 'utf-8'.
 |  errors defaults to 'strict'.
 |
 |  Methods defined here:
 |
 |  __add__(self, value, /)
 |      Return self+value.
 |
 |  __contains__(self, key, /)
 |      Return bool(key in self).
 |
 |  __eq__(self, value, /)
 |      Return self==value.
 |
 |  __format__(self, format_spec, /)
 |      Return a formatted version of the string as described by format_spec.
 |
 |  __ge__(self, value, /)
 |      Return self>=value.
 |
 |  __getitem__(self, key, /)
 |      Return self[key].
 |
 |  __getnewargs__(self, /)
 |
 |  __gt__(self, v

In [22]:
# type casting 
job_id = 101
float(job_id)


101.0

In [23]:
feel='fresh'
print(feel.upper())
print(feel.lower())
print(feel.__add__(' mind'))
print(feel.replace('f', 'c'))
print(feel) # original string is not changed
print(feel.split(sep='e'))


FRESH
fresh
fresh mind
cresh
fresh
['fr', 'sh']


In [24]:
baby_age='0123456789'
','.join(baby_age)

'0,1,2,3,4,5,6,7,8,9'

In [25]:
print(5//2)
c=5
c += 2
print(c)   
print(1 == 2 )
if c > 5:
    print("c is greater than 5")
elif c == 5:
    print("c is equal to 5")
else:
    print("c is less than 5")


2
7
False
c is greater than 5


In [26]:
skills=['english','trader','developer']
print(skills)
skills.append('data scientist')
print(skills)
print(skills[1])
skills.pop(2)
print(skills)
skills.insert(3, 'developer')
skills
skills[0:1]  #slicing
skills

['english', 'trader', 'developer']
['english', 'trader', 'developer', 'data scientist']
trader
['english', 'trader', 'data scientist']


['english', 'trader', 'data scientist', 'developer']

In [27]:
info={'language':'english', 'skill':'SoftwareDeveloper'}
info
print(info['language'])
info.update({'skill':'DataScientist'})
print(info)

english
{'language': 'english', 'skill': 'DataScientist'}


In [28]:
set={'cooker','developer','data scientist','data analyst'}
print(set)
set.add('data engineer')
print(set)
set.remove('developer')
print(set)

{'developer', 'data analyst', 'cooker', 'data scientist'}
{'developer', 'data engineer', 'data analyst', 'data scientist', 'cooker'}
{'data engineer', 'data analyst', 'data scientist', 'cooker'}


In [29]:
# Tuples are immutable
introduce_yourself=('okan','naci')
print(introduce_yourself)
 

('okan', 'naci')


In [30]:
tuple(range(2,5))

(2, 3, 4)

In [31]:
print(1 and 1)
print(1 or 0)
print(1 and 0)
print(not 1)

1
1
0
False


In [32]:
nums=[0,1,2,3,4,5,6]
for i in nums:
    print(i)
dataAge={
    'alice': 25,
    'bob': 30,
    'charlie': 35
}
print(dataAge)

for name, age in dataAge.items():
    print(f"{name} is {age} years old")

0
1
2
3
4
5
6
{'alice': 25, 'bob': 30, 'charlie': 35}
alice is 25 years old
bob is 30 years old
charlie is 35 years old


In [33]:
#list comprehension
ages=[2,3,4,5,4,6]
squared = [x**2 for x in ages ]
print(squared)


[4, 9, 16, 25, 16, 36]


In [34]:
job_roles = [
    {'role': 'Data Analyst', 'skills': ['Python', 'SQL', 'Excel']},
    {'role': 'Data Scientist', 'skills': ['Python', 'R', 'Machine Learning', 'Deep Learning']},
    {'role': 'Machine Learning Engineer', 'skills': ['Python', 'TensorFlow', 'PyTorch', 'Scikit-Learn']},
    {'role': 'Data Engineer', 'skills': ['Python', 'Apache Spark', 'Hadoop', 'SQL']},
    {'role': 'Business Intelligence Analyst', 'skills': ['Python', 'SQL', 'Tableau', 'Power BI', 'Excel']},
    {'role': 'Quantitative Analyst', 'skills': ['R', 'Python', 'MATLAB', 'Statistics']},
    {'role': 'Operations Analyst', 'skills': ['Python', 'SQL', 'Data Visualization', 'Process Improvement']},
    {'role': 'Database Administrator', 'skills': ['SQL', 'Oracle', 'MySQL', 'Database Management']},
    {'role': 'AI Engineer', 'skills': ['Python', 'TensorFlow', 'PyTorch', 'Computer Vision']},
    {'role': 'Statistician', 'skills': ['R', 'SAS', 'Python', 'Statistical Modeling']}
]
for job in job_roles:  
    print(job['role']) 
    print(job['skills'])



Data Analyst
['Python', 'SQL', 'Excel']
Data Scientist
['Python', 'R', 'Machine Learning', 'Deep Learning']
Machine Learning Engineer
['Python', 'TensorFlow', 'PyTorch', 'Scikit-Learn']
Data Engineer
['Python', 'Apache Spark', 'Hadoop', 'SQL']
Business Intelligence Analyst
['Python', 'SQL', 'Tableau', 'Power BI', 'Excel']
Quantitative Analyst
['R', 'Python', 'MATLAB', 'Statistics']
Operations Analyst
['Python', 'SQL', 'Data Visualization', 'Process Improvement']
Database Administrator
['SQL', 'Oracle', 'MySQL', 'Database Management']
AI Engineer
['Python', 'TensorFlow', 'PyTorch', 'Computer Vision']
Statistician
['R', 'SAS', 'Python', 'Statistical Modeling']


In [35]:
def calculate_bmi(weight_kg: float, height_m: float) -> str:
    if height_m <= 0:
        return "Error: Height must be greater than zero."
    if weight_kg <= 0:
        return "Error: Weight must be greater than zero."

    bmi = weight_kg / (height_m ** 2)
    
    if bmi < 18.5:
        category = "Underweight"
    elif 18.5 <= bmi < 24.9:
        category = "Normal weight"
    elif 25 <= bmi < 29.9:
        category = "Overweight"
    else:
        category = "Obesity"
    
    return f"Your BMI is {bmi:.2f} ({category})."

calculate_bmi(70, 1.75)

'Your BMI is 22.86 (Normal weight).'

In [36]:
a=23
b=45
result=lambda a,b:a*b
print(result(a,b))


1035


In [37]:
import importlib
import myNumModule as m  # Import your module with an alias

# Reload module in case you edited it after the first import
importlib.reload(m)
print(m.who_am_i("Okan", "Naci"))


I am Okan Naci, a number module.


In [38]:
import statistics as st 
ages=[23,45,67,89,12,34,56]
st.mean(ages)

46.57142857142857

In [39]:
#clean the data 
data_science_jobs = [
    {'job_title': 'Data Scientist', 'job_skills': "['Python', 'SQL', 'Machine Learning']", 'job_date': '2023-05-12'},
    {'job_title': 'Machine Learning Engineer', 'job_skills': "['Python', 'TensorFlow', 'Deep Learning']", 'job_date': '2023-05-15'},
    {'job_title': 'Data Analyst', 'job_skills': "['SQL', 'R', 'Tableau']", 'job_date': '2023-05-10'},
    {'job_title': 'Business Intelligence Developer', 'job_skills': "['SQL', 'PowerBI', 'Data Warehousing']", 'job_date': '2023-05-08'},
    {'job_title': 'Data Engineer', 'job_skills': "['Python', 'Spark', 'Hadoop']", 'job_date': '2023-05-18'},
    {'job_title': 'AI Specialist', 'job_skills': "['Python', 'PyTorch', 'AI Ethics']", 'job_date': '2023-05-20'}
]

In [40]:
from datetime import datetime
datetime.now()

datetime.datetime(2025, 9, 6, 11, 32, 39, 171102)

In [41]:
date=data_science_jobs[0]['job_date']
print(datetime.strptime(date, '%Y-%m-%d'))

2023-05-12 00:00:00


In [42]:
import ast 
for job in data_science_jobs:
    job['job_date']=datetime.strptime(job['job_date'], '%Y-%m-%d')
    job['job_skills']=ast.literal_eval(job['job_skills'])

In [43]:
data_science_jobs

[{'job_title': 'Data Scientist',
  'job_skills': ['Python', 'SQL', 'Machine Learning'],
  'job_date': datetime.datetime(2023, 5, 12, 0, 0)},
 {'job_title': 'Machine Learning Engineer',
  'job_skills': ['Python', 'TensorFlow', 'Deep Learning'],
  'job_date': datetime.datetime(2023, 5, 15, 0, 0)},
 {'job_title': 'Data Analyst',
  'job_skills': ['SQL', 'R', 'Tableau'],
  'job_date': datetime.datetime(2023, 5, 10, 0, 0)},
 {'job_title': 'Business Intelligence Developer',
  'job_skills': ['SQL', 'PowerBI', 'Data Warehousing'],
  'job_date': datetime.datetime(2023, 5, 8, 0, 0)},
 {'job_title': 'Data Engineer',
  'job_skills': ['Python', 'Spark', 'Hadoop'],
  'job_date': datetime.datetime(2023, 5, 18, 0, 0)},
 {'job_title': 'AI Specialist',
  'job_skills': ['Python', 'PyTorch', 'AI Ethics'],
  'job_date': datetime.datetime(2023, 5, 20, 0, 0)}]

In [53]:
import os
size = os.path.getsize("ai_job_dataset.csv")
print(size)

2591213


In [56]:
import pandas as pd 
contents = pd.read_csv("ai_job_dataset.csv")
contents['education_required']

0         Bachelor
1           Master
2        Associate
3              PhD
4           Master
           ...    
14995     Bachelor
14996       Master
14997    Associate
14998          PhD
14999          PhD
Name: education_required, Length: 15000, dtype: object

In [2]:
import numpy as np
arr = np.array([1,2,3,4])
multipled=arr * 2
multipled


array([2, 4, 6, 8])

In [3]:
arr = np.array([1, 2, 3], dtype=np.int16)  # Uses 16-bit integers
arr.dtype

dtype('int16')

In [16]:
class BaseSalary:
    def __init__(self, base_salary,symbol='$'):
        self.base_salary = f"{symbol} {base_salary}"
        pass

In [17]:
jacks=BaseSalary(10000)
jacks.base_salary   

'$ 10000'

In [20]:
import random as rm 
salary_list = [rm.randint(10000,50000) for _ in range(5)]

In [2]:
import numpy as np


In [3]:
A=np.ones((3,4))
A

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [4]:
v = np.array([1,2,3,4])

In [6]:
B=A+v
B

array([[2., 3., 4., 5.],
       [2., 3., 4., 5.],
       [2., 3., 4., 5.]])

In [13]:
arr = np.array([[1,2,3],[4,5,6]])
size=arr.shape
size

(2, 3)

In [17]:
print(arr.sum(axis=0))  #sum of each column
print(arr.sum(axis=1))

[5 7 9]
[ 6 15]


In [30]:
arr = np.array([1,2,3,4,5,6])
arr = arr.reshape(2,3)
arr
arr.ravel()
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [32]:
arr.T
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [31]:
arr[-1]

array([4, 5, 6])

In [33]:
arr[arr>1]

array([2, 3, 4, 5, 6])

In [35]:
arr[:,0]

array([1, 4])

In [38]:
np_array=np.arange(10)
print(np_array)
print(np_array*3)

[0 1 2 3 4 5 6 7 8 9]
[ 0  3  6  9 12 15 18 21 24 27]


In [40]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])

print("A @ B =\n", A @ B)          # matrix multiplication
print("inverse:\n", np.linalg.inv(A))
print("eigenvalues:", np.linalg.eigvals(A))


A @ B =
 [[19 22]
 [43 50]]
inverse:
 [[-2.   1. ]
 [ 1.5 -0.5]]
eigenvalues: [-0.37228132  5.37228132]


In [43]:
rng = np.random.default_rng(42)
print(rng.random((2,3)))          # uniform [0,1)
print(rng.integers(0, 10, size=5)) # random integers
print(rng.normal(0, 1, size=5))    # Gaussian


[[0.77395605 0.43887844 0.85859792]
 [0.69736803 0.09417735 0.97562235]]
[7 7 7 7 5]
[-0.85304393  0.87939797  0.77779194  0.0660307   1.12724121]


In [45]:
X = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])

mean = X.mean(axis=0)
std = X.std(axis=0)
X_norm = (X - mean) / std
print("Mean:\n", mean)
print("Standard Deviation:\n", std)
print(X_norm)


Mean:
 [4. 5. 6.]
Standard Deviation:
 [2.44948974 2.44948974 2.44948974]
[[-1.22474487 -1.22474487 -1.22474487]
 [ 0.          0.          0.        ]
 [ 1.22474487  1.22474487  1.22474487]]
