In [1]:
print("Jupyter is working in VS Code!")

Jupyter is working in VS Code!


In [2]:
L=[]
for n in range(5):
        L.append(n**2)
        print(L)

[0]
[0, 1]
[0, 1, 4]
[0, 1, 4, 9]
[0, 1, 4, 9, 16]


In [3]:
base_salary=10000
bonus_rate=.10
total_salary=base_salary*(1+bonus_rate)
total_salary

11000.0

In [4]:
type(total_salary)

float

In [5]:
id(total_salary) 
#each variable in Python has a unique id

3031292541584

In [6]:
def introduce_yourself(name, age):
    print(f"Hello, my name is {name}.\nI am {age} years old.")
introduce_yourself("okan", 22)

Hello, my name is okan.
I am 22 years old.


In [7]:
job_title = "Data Scientist"
job_location = "New York"
job_salary = 120000
class Job:
    def __init__(self, title, location, salary):
        self.title = title
        self.location = location
        self.salary = salary
        return print(f"Job Title: {self.title}\nLocation: {self.location}\nSalary: ${self.salary}")
job_1=Job(job_title, job_location, job_salary)
job_1.title

Job Title: Data Scientist
Location: New York
Salary: $120000


'Data Scientist'

In [8]:
help(str)

Help on class str in module builtins:

class str(object)
 |  str(object='') -> str
 |  str(bytes_or_buffer[, encoding[, errors]]) -> str
 |
 |  Create a new string object from the given object. If encoding or
 |  errors is specified, then the object must expose a data buffer
 |  that will be decoded using the given encoding and error handler.
 |  Otherwise, returns the result of object.__str__() (if defined)
 |  or repr(object).
 |  encoding defaults to 'utf-8'.
 |  errors defaults to 'strict'.
 |
 |  Methods defined here:
 |
 |  __add__(self, value, /)
 |      Return self+value.
 |
 |  __contains__(self, key, /)
 |      Return bool(key in self).
 |
 |  __eq__(self, value, /)
 |      Return self==value.
 |
 |  __format__(self, format_spec, /)
 |      Return a formatted version of the string as described by format_spec.
 |
 |  __ge__(self, value, /)
 |      Return self>=value.
 |
 |  __getitem__(self, key, /)
 |      Return self[key].
 |
 |  __getnewargs__(self, /)
 |
 |  __gt__(self, v

In [9]:
# type casting 
job_id = 101
float(job_id)


101.0

In [10]:
feel='fresh'
print(feel.upper())
print(feel.lower())
print(feel.__add__(' mind'))
print(feel.replace('f', 'c'))
print(feel) # original string is not changed
print(feel.split(sep='e'))


FRESH
fresh
fresh mind
cresh
fresh
['fr', 'sh']


In [11]:
baby_age='0123456789'
','.join(baby_age)

'0,1,2,3,4,5,6,7,8,9'

In [12]:
print(5//2)
c=5
c += 2
print(c)   
print(1 == 2 )
if c > 5:
    print("c is greater than 5")
elif c == 5:
    print("c is equal to 5")
else:
    print("c is less than 5")


2
7
False
c is greater than 5


In [13]:
skills=['english','trader','developer']
print(skills)
skills.append('data scientist')
print(skills)
print(skills[1])
skills.pop(2)
print(skills)
skills.insert(3, 'developer')
skills
skills[0:1]  #slicing
skills

['english', 'trader', 'developer']
['english', 'trader', 'developer', 'data scientist']
trader
['english', 'trader', 'data scientist']


['english', 'trader', 'data scientist', 'developer']

In [14]:
info={'language':'english', 'skill':'SoftwareDeveloper'}
info
print(info['language'])
info.update({'skill':'DataScientist'})
print(info)

english
{'language': 'english', 'skill': 'DataScientist'}


In [15]:
set={'cooker','developer','data scientist','data analyst'}
print(set)
set.add('data engineer')
print(set)
set.remove('developer')
print(set)

{'cooker', 'developer', 'data scientist', 'data analyst'}
{'cooker', 'data engineer', 'data analyst', 'data scientist', 'developer'}
{'cooker', 'data engineer', 'data analyst', 'data scientist'}


In [16]:
# Tuples are immutable
introduce_yourself=('okan','naci')
print(introduce_yourself)
 

('okan', 'naci')


In [17]:
tuple(range(2,5))

(2, 3, 4)

In [18]:
print(1 and 1)
print(1 or 0)
print(1 and 0)
print(not 1)

1
1
0
False


In [19]:
nums=[0,1,2,3,4,5,6]
for i in nums:
    print(i)
dataAge={
    'alice': 25,
    'bob': 30,
    'charlie': 35
}
print(dataAge)

for name, age in dataAge.items():
    print(f"{name} is {age} years old")

0
1
2
3
4
5
6
{'alice': 25, 'bob': 30, 'charlie': 35}
alice is 25 years old
bob is 30 years old
charlie is 35 years old


In [20]:
#list comprehension
ages=[2,3,4,5,4,6]
squared = [x**2 for x in ages ]
print(squared)


[4, 9, 16, 25, 16, 36]


In [21]:
job_roles = [
    {'role': 'Data Analyst', 'skills': ['Python', 'SQL', 'Excel']},
    {'role': 'Data Scientist', 'skills': ['Python', 'R', 'Machine Learning', 'Deep Learning']},
    {'role': 'Machine Learning Engineer', 'skills': ['Python', 'TensorFlow', 'PyTorch', 'Scikit-Learn']},
    {'role': 'Data Engineer', 'skills': ['Python', 'Apache Spark', 'Hadoop', 'SQL']},
    {'role': 'Business Intelligence Analyst', 'skills': ['Python', 'SQL', 'Tableau', 'Power BI', 'Excel']},
    {'role': 'Quantitative Analyst', 'skills': ['R', 'Python', 'MATLAB', 'Statistics']},
    {'role': 'Operations Analyst', 'skills': ['Python', 'SQL', 'Data Visualization', 'Process Improvement']},
    {'role': 'Database Administrator', 'skills': ['SQL', 'Oracle', 'MySQL', 'Database Management']},
    {'role': 'AI Engineer', 'skills': ['Python', 'TensorFlow', 'PyTorch', 'Computer Vision']},
    {'role': 'Statistician', 'skills': ['R', 'SAS', 'Python', 'Statistical Modeling']}
]
for job in job_roles:  
    print(job['role']) 
    print(job['skills'])



Data Analyst
['Python', 'SQL', 'Excel']
Data Scientist
['Python', 'R', 'Machine Learning', 'Deep Learning']
Machine Learning Engineer
['Python', 'TensorFlow', 'PyTorch', 'Scikit-Learn']
Data Engineer
['Python', 'Apache Spark', 'Hadoop', 'SQL']
Business Intelligence Analyst
['Python', 'SQL', 'Tableau', 'Power BI', 'Excel']
Quantitative Analyst
['R', 'Python', 'MATLAB', 'Statistics']
Operations Analyst
['Python', 'SQL', 'Data Visualization', 'Process Improvement']
Database Administrator
['SQL', 'Oracle', 'MySQL', 'Database Management']
AI Engineer
['Python', 'TensorFlow', 'PyTorch', 'Computer Vision']
Statistician
['R', 'SAS', 'Python', 'Statistical Modeling']


In [22]:
def calculate_bmi(weight_kg: float, height_m: float) -> str:
    if height_m <= 0:
        return "Error: Height must be greater than zero."
    if weight_kg <= 0:
        return "Error: Weight must be greater than zero."

    bmi = weight_kg / (height_m ** 2)
    
    if bmi < 18.5:
        category = "Underweight"
    elif 18.5 <= bmi < 24.9:
        category = "Normal weight"
    elif 25 <= bmi < 29.9:
        category = "Overweight"
    else:
        category = "Obesity"
    
    return f"Your BMI is {bmi:.2f} ({category})."

calculate_bmi(70, 1.75)

'Your BMI is 22.86 (Normal weight).'

In [23]:
a=23
b=45
result=lambda a,b:a*b
print(result(a,b))


1035


In [24]:
import importlib
import myNumModule as m  # Import your module with an alias

# Reload module in case you edited it after the first import
importlib.reload(m)
print(m.who_am_i("Okan", "Naci"))


I am Okan Naci, a number module.


In [25]:
import statistics as st 
ages=[23,45,67,89,12,34,56]
st.mean(ages)

46.57142857142857

In [26]:
#clean the data 
data_science_jobs = [
    {'job_title': 'Data Scientist', 'job_skills': "['Python', 'SQL', 'Machine Learning']", 'job_date': '2023-05-12'},
    {'job_title': 'Machine Learning Engineer', 'job_skills': "['Python', 'TensorFlow', 'Deep Learning']", 'job_date': '2023-05-15'},
    {'job_title': 'Data Analyst', 'job_skills': "['SQL', 'R', 'Tableau']", 'job_date': '2023-05-10'},
    {'job_title': 'Business Intelligence Developer', 'job_skills': "['SQL', 'PowerBI', 'Data Warehousing']", 'job_date': '2023-05-08'},
    {'job_title': 'Data Engineer', 'job_skills': "['Python', 'Spark', 'Hadoop']", 'job_date': '2023-05-18'},
    {'job_title': 'AI Specialist', 'job_skills': "['Python', 'PyTorch', 'AI Ethics']", 'job_date': '2023-05-20'}
]

In [27]:
from datetime import datetime
datetime.now()

datetime.datetime(2025, 9, 13, 12, 52, 54, 971384)

In [28]:
date=data_science_jobs[0]['job_date']
print(datetime.strptime(date, '%Y-%m-%d'))

2023-05-12 00:00:00


In [29]:
import ast 
for job in data_science_jobs:
    job['job_date']=datetime.strptime(job['job_date'], '%Y-%m-%d')
    job['job_skills']=ast.literal_eval(job['job_skills'])

In [30]:
data_science_jobs

[{'job_title': 'Data Scientist',
  'job_skills': ['Python', 'SQL', 'Machine Learning'],
  'job_date': datetime.datetime(2023, 5, 12, 0, 0)},
 {'job_title': 'Machine Learning Engineer',
  'job_skills': ['Python', 'TensorFlow', 'Deep Learning'],
  'job_date': datetime.datetime(2023, 5, 15, 0, 0)},
 {'job_title': 'Data Analyst',
  'job_skills': ['SQL', 'R', 'Tableau'],
  'job_date': datetime.datetime(2023, 5, 10, 0, 0)},
 {'job_title': 'Business Intelligence Developer',
  'job_skills': ['SQL', 'PowerBI', 'Data Warehousing'],
  'job_date': datetime.datetime(2023, 5, 8, 0, 0)},
 {'job_title': 'Data Engineer',
  'job_skills': ['Python', 'Spark', 'Hadoop'],
  'job_date': datetime.datetime(2023, 5, 18, 0, 0)},
 {'job_title': 'AI Specialist',
  'job_skills': ['Python', 'PyTorch', 'AI Ethics'],
  'job_date': datetime.datetime(2023, 5, 20, 0, 0)}]

In [31]:
import os
size = os.path.getsize("ai_job_dataset.csv")
print(size)

2591213


In [32]:
import pandas as pd 
contents = pd.read_csv("ai_job_dataset.csv")
contents['education_required']

0         Bachelor
1           Master
2        Associate
3              PhD
4           Master
           ...    
14995     Bachelor
14996       Master
14997    Associate
14998          PhD
14999          PhD
Name: education_required, Length: 15000, dtype: object

In [33]:
import numpy as np
arr = np.array([1,2,3,4])
multipled=arr * 2
multipled


array([2, 4, 6, 8])

In [34]:
arr = np.array([1, 2, 3], dtype=np.int16)  # Uses 16-bit integers
arr.dtype

dtype('int16')

In [35]:
class BaseSalary:
    def __init__(self, base_salary,symbol='$'):
        self.base_salary = f"{symbol} {base_salary}"
        pass

In [36]:
jacks=BaseSalary(10000)
jacks.base_salary   

'$ 10000'

In [37]:
import random as rm 
salary_list = [rm.randint(10000,50000) for _ in range(5)]

In [38]:
import numpy as np


In [39]:
A=np.ones((3,4))
A

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [40]:
v = np.array([1,2,3,4])

In [41]:
B=A+v
B

array([[2., 3., 4., 5.],
       [2., 3., 4., 5.],
       [2., 3., 4., 5.]])

In [42]:
arr = np.array([[1,2,3],[4,5,6]])
size=arr.shape
size

(2, 3)

In [43]:
print(arr.sum(axis=0))  #sum of each column
print(arr.sum(axis=1))

[5 7 9]
[ 6 15]


In [44]:
arr = np.array([1,2,3,4,5,6])
arr = arr.reshape(2,3)
arr
arr.ravel()
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [45]:
arr.T
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [46]:
arr[-1]

array([4, 5, 6])

In [47]:
arr[arr>1]

array([2, 3, 4, 5, 6])

In [48]:
arr[:,0]

array([1, 4])

In [49]:
np_array=np.arange(10)
print(np_array)
print(np_array*3)

[0 1 2 3 4 5 6 7 8 9]
[ 0  3  6  9 12 15 18 21 24 27]


In [50]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])

print("A @ B =\n", A @ B)          # matrix multiplication
print("inverse:\n", np.linalg.inv(A))
print("eigenvalues:", np.linalg.eigvals(A))


A @ B =
 [[19 22]
 [43 50]]
inverse:
 [[-2.   1. ]
 [ 1.5 -0.5]]
eigenvalues: [-0.37228132  5.37228132]


In [51]:
rng = np.random.default_rng(42)
print(rng.random((2,3)))          # uniform [0,1)
print(rng.integers(0, 10, size=5)) # random integers
print(rng.normal(0, 1, size=5))    # Gaussian


[[0.77395605 0.43887844 0.85859792]
 [0.69736803 0.09417735 0.97562235]]
[7 7 7 7 5]
[-0.85304393  0.87939797  0.77779194  0.0660307   1.12724121]


In [52]:
X = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])

mean = X.mean(axis=0)
std = X.std(axis=0)
X_norm = (X - mean) / std
print("Mean:\n", mean)
print("Standard Deviation:\n", std)
print(X_norm)


Mean:
 [4. 5. 6.]
Standard Deviation:
 [2.44948974 2.44948974 2.44948974]
[[-1.22474487 -1.22474487 -1.22474487]
 [ 0.          0.          0.        ]
 [ 1.22474487  1.22474487  1.22474487]]


In [53]:
import pandas as pd
data = {
    "Name": ["Alice", "Bob", "Charlie", "Diana", "Evan"],
    "Department": ["HR", "IT", "IT", "Finance", "HR"],
    "Salary": [50000, 60000, 70000, 80000, 55000],
    "Joining_Date": ["2020-01-10", "2019-03-15", "2021-06-01", "2018-07-20", "2020-05-25"]
}
df = pd.DataFrame(data)
df["Joining_Date"] = pd.to_datetime(df["Joining_Date"])
print(df)


      Name Department  Salary Joining_Date
0    Alice         HR   50000   2020-01-10
1      Bob         IT   60000   2019-03-15
2  Charlie         IT   70000   2021-06-01
3    Diana    Finance   80000   2018-07-20
4     Evan         HR   55000   2020-05-25


In [54]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype         
---  ------        --------------  -----         
 0   Name          5 non-null      object        
 1   Department    5 non-null      object        
 2   Salary        5 non-null      int64         
 3   Joining_Date  5 non-null      datetime64[ns]
dtypes: datetime64[ns](1), int64(1), object(2)
memory usage: 292.0+ bytes


In [55]:
df.dtypes

Name                    object
Department              object
Salary                   int64
Joining_Date    datetime64[ns]
dtype: object

In [56]:
df['Salary'].mean()

np.float64(63000.0)

In [57]:
salarys=df['Salary']
salarys

0    50000
1    60000
2    70000
3    80000
4    55000
Name: Salary, dtype: int64

In [58]:
df[["Name", "Salary"]]

Name  Salary
0    Alice   50000
1      Bob   60000
2  Charlie   70000
3    Diana   80000
4     Evan   55000

In [59]:
df=pd.read_csv("ai_job_dataset.csv")

In [60]:
df

job_id                    job_title  salary_usd salary_currency  \
0      AI00001        AI Research Scientist       90376             USD   
1      AI00002         AI Software Engineer       61895             USD   
2      AI00003                AI Specialist      152626             USD   
3      AI00004                 NLP Engineer       80215             USD   
4      AI00005                AI Consultant       54624             EUR   
...        ...                          ...         ...             ...   
14995  AI14996            Robotics Engineer       38604             USD   
14996  AI14997  Machine Learning Researcher       57811             GBP   
14997  AI14998                 NLP Engineer      189490             USD   
14998  AI14999                   Head of AI       79461             EUR   
14999  AI15000     Computer Vision Engineer       56481             USD   

      experience_level employment_type company_location company_size  \
0                   SE              CT            China            M   
1                   EN              CT           Canada            M   
2                   MI              FL      Switzerland            L   
3                   SE              FL            India            M   
4                   EN              PT           France            S   
...                ...             ...              ...          ...   
14995               EN              FL          Finland            S   
14996               EN              CT   United Kingdom            M   
14997               EX              CT      South Korea            L   
14998               EN              FT      Netherlands            M   
14999               MI              PT          Austria            S   

      employee_residence  remote_ratio  \
0                  China            50   
1                Ireland           100   
2            South Korea             0   
3                  India            50   
4              Singapore           100   
...                  ...           ...   
14995            Finland            50   
14996     United Kingdom             0   
14997        South Korea            50   
14998        Netherlands             0   
14999            Austria            50   

                                       required_skills education_required  \
0             Tableau, PyTorch, Kubernetes, Linux, NLP           Bachelor   
1      Deep Learning, AWS, Mathematics, Python, Docker             Master   
2         Kubernetes, Deep Learning, Java, Hadoop, NLP          Associate   
3                            Scala, SQL, Linux, Python                PhD   
4                         MLOps, Java, Tableau, Python             Master   
...                                                ...                ...   
14995                          Java, Kubernetes, Azure           Bachelor   
14996          Mathematics, Docker, SQL, Deep Learning             Master   
14997                                Scala, Spark, NLP          Associate   
14998        Java, Computer Vision, Python, TensorFlow                PhD   
14999    Scala, Azure, Deep Learning, GCP, Mathematics                PhD   

       years_experience       industry posting_date application_deadline  \
0                     9     Automotive   2024-10-18           2024-11-07   
1                     1          Media   2024-11-20           2025-01-11   
2                     2      Education   2025-03-18           2025-04-07   
3                     7     Consulting   2024-12-23           2025-02-24   
4                     0          Media   2025-04-15           2025-06-23   
...                 ...            ...          ...                  ...   
14995                 1         Energy   2025-02-06           2025-03-25   
14996                 0     Government   2024-10-16           2024-10-30   
14997                17  Manufacturing   2024-03-19           2024-05-02   
14998                 1    Real Estate   2024-03-22 

In [61]:
df['salary_usd'].head()

0     90376
1     61895
2    152626
3     80215
4     54624
Name: salary_usd, dtype: int64

In [62]:
highes_paid=df[df['salary_usd']>390000]
highes_paid

job_id                    job_title  salary_usd salary_currency  \
2309   AI02310                 AI Architect      398084             USD   
9891   AI09892  Machine Learning Researcher      399095             USD   
12499  AI12500        AI Research Scientist      394917             USD   
12803  AI12804                AI Specialist      390292             USD   

      experience_level employment_type company_location company_size  \
2309                EX              CT      Switzerland            L   
9891                EX              PT      Switzerland            L   
12499               EX              CT      Switzerland            L   
12803               EX              FT      Switzerland            L   

      employee_residence  remote_ratio  \
2309         Switzerland           100   
9891         Switzerland             0   
12499        Switzerland            50   
12803        Switzerland            50   

                                  required_skills education_required  \
2309           Python, Linux, Tableau, TensorFlow          Associate   
9891                    Linux, Python, TensorFlow             Master   
12499          Scala, PyTorch, Spark, Docker, Git             Master   
12803  Java, SQL, PyTorch, Statistics, TensorFlow          Associate   

       years_experience     industry posting_date application_deadline  \
2309                 15   Automotive   2024-12-30           2025-02-20   
9891                 10       Retail   2024-07-10           2024-09-02   
12499                12  Real Estate   2024-06-04           2024-08-13   
12803                11  Real Estate   2024-12-27           2025-01-24   

       job_description_length  benefits_score                company_name  
2309                     1979            10.0              Future Systems  
9891                     2277             9.7                TechCorp Inc  
12499                    1310             6.6  Machine Intelligence Group  
12803                    1900             7.5              DataVision Ltd

In [63]:
row0_name = df.loc[0, "job_title"] 
row0_name

'AI Research Scientist'

In [64]:
first_row_third_col = df.iloc[0, 2]  # first row, 3rd column
first_row_third_col

np.int64(90376)

In [65]:
us_highes_paid = df[(df['salary_currency']=='USD') & (df['salary_usd']>380000)]

In [66]:
us_highes_paid

job_id                    job_title  salary_usd salary_currency  \
317    AI00318               Data Scientist      388754             USD   
2309   AI02310                 AI Architect      398084             USD   
5483   AI05484                 AI Architect      383142             USD   
9891   AI09892  Machine Learning Researcher      399095             USD   
10468  AI10469           AI Product Manager      381575             USD   
12499  AI12500        AI Research Scientist      394917             USD   
12803  AI12804                AI Specialist      390292             USD   

      experience_level employment_type company_location company_size  \
317                 EX              CT      Switzerland            L   
2309                EX              CT      Switzerland            L   
5483                EX              PT      Switzerland            L   
9891                EX              PT      Switzerland            L   
10468               EX              PT      Switzerland            L   
12499               EX              CT      Switzerland            L   
12803               EX              FT      Switzerland            L   

      employee_residence  remote_ratio  \
317        United States             0   
2309         Switzerland           100   
5483         Switzerland            50   
9891         Switzerland             0   
10468            Denmark            50   
12499        Switzerland            50   
12803        Switzerland            50   

                                         required_skills education_required  \
317                          Docker, Python, Mathematics             Master   
2309                  Python, Linux, Tableau, TensorFlow          Associate   
5483                     Git, Python, Hadoop, TensorFlow             Master   
9891                           Linux, Python, TensorFlow             Master   
10468  Python, Git, Data Visualization, Spark, Comput...          Associate   
12499                 Scala, PyTorch, Spark, Docker, Git             Master   
12803         Java, SQL, PyTorch, Statistics, TensorFlow          Associate   

       years_experience        industry posting_date application_deadline  \
317                  16  Transportation   2024-06-20           2024-08-11   
2309                 15      Automotive   2024-12-30           2025-02-20   
5483                 12      Technology   2025-01-13           2025-01-27   
9891                 10          Retail   2024-07-10           2024-09-02   
10468                10          Energy   2024-03-27           2024-05-28   
12499                12     Real Estate   2024-06-04           2024-08-13   
12803                11     Real Estate   2024-12-27           2025-01-24   

       job_description_length  benefits_score                company_name  
317                       829             8.6           DeepTech Ventures  
2309                     1979            10.0              Future Systems  
5483                     1463             9.2              Future Systems  
9891                     2277             9.7                TechCorp Inc  
10468                    1570             9.7          Neural Networks Co  
12499                    1310             6.6  Machine Intelligence Group  
12803                    1900             7.5              DataVision Ltd

In [67]:
df.isna().sum()

job_id                    0
job_title                 0
salary_usd                0
salary_currency           0
experience_level          0
employment_type           0
company_location          0
company_size              0
employee_residence        0
remote_ratio              0
required_skills           0
education_required        0
years_experience          0
industry                  0
posting_date              0
application_deadline      0
job_description_length    0
benefits_score            0
company_name              0
dtype: int64

In [68]:
df['salary_usd'].fillna(df['salary_usd'].mean(), inplace=True)#fill missing walues 

C:\Users\mypc\AppData\Local\Temp\ipykernel_11084\176212075.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['salary_usd'].fillna(df['salary_usd'].mean(), inplace=True)#fill missing walues


In [69]:
df.dropna(axis=0, how='any', inplace=False)#it does not modify the original DataFrame; instead, it returns a new one with NaN-rows removed.

job_id                    job_title  salary_usd salary_currency  \
0      AI00001        AI Research Scientist       90376             USD   
1      AI00002         AI Software Engineer       61895             USD   
2      AI00003                AI Specialist      152626             USD   
3      AI00004                 NLP Engineer       80215             USD   
4      AI00005                AI Consultant       54624             EUR   
...        ...                          ...         ...             ...   
14995  AI14996            Robotics Engineer       38604             USD   
14996  AI14997  Machine Learning Researcher       57811             GBP   
14997  AI14998                 NLP Engineer      189490             USD   
14998  AI14999                   Head of AI       79461             EUR   
14999  AI15000     Computer Vision Engineer       56481             USD   

      experience_level employment_type company_location company_size  \
0                   SE              CT            China            M   
1                   EN              CT           Canada            M   
2                   MI              FL      Switzerland            L   
3                   SE              FL            India            M   
4                   EN              PT           France            S   
...                ...             ...              ...          ...   
14995               EN              FL          Finland            S   
14996               EN              CT   United Kingdom            M   
14997               EX              CT      South Korea            L   
14998               EN              FT      Netherlands            M   
14999               MI              PT          Austria            S   

      employee_residence  remote_ratio  \
0                  China            50   
1                Ireland           100   
2            South Korea             0   
3                  India            50   
4              Singapore           100   
...                  ...           ...   
14995            Finland            50   
14996     United Kingdom             0   
14997        South Korea            50   
14998        Netherlands             0   
14999            Austria            50   

                                       required_skills education_required  \
0             Tableau, PyTorch, Kubernetes, Linux, NLP           Bachelor   
1      Deep Learning, AWS, Mathematics, Python, Docker             Master   
2         Kubernetes, Deep Learning, Java, Hadoop, NLP          Associate   
3                            Scala, SQL, Linux, Python                PhD   
4                         MLOps, Java, Tableau, Python             Master   
...                                                ...                ...   
14995                          Java, Kubernetes, Azure           Bachelor   
14996          Mathematics, Docker, SQL, Deep Learning             Master   
14997                                Scala, Spark, NLP          Associate   
14998        Java, Computer Vision, Python, TensorFlow                PhD   
14999    Scala, Azure, Deep Learning, GCP, Mathematics                PhD   

       years_experience       industry posting_date application_deadline  \
0                     9     Automotive   2024-10-18           2024-11-07   
1                     1          Media   2024-11-20           2025-01-11   
2                     2      Education   2025-03-18           2025-04-07   
3                     7     Consulting   2024-12-23           2025-02-24   
4                     0          Media   2025-04-15           2025-06-23   
...                 ...            ...          ...                  ...   
14995                 1         Energy   2025-02-06           2025-03-25   
14996                 0     Government   2024-10-16           2024-10-30   
14997                17  Manufacturing   2024-03-19           2024-05-02   
14998                 1    Real Estate   2024-03-22 

In [70]:
df.drop_duplicates(subset=["job_id", "job_title"], keep="first", inplace=False)


job_id                    job_title  salary_usd salary_currency  \
0      AI00001        AI Research Scientist       90376             USD   
1      AI00002         AI Software Engineer       61895             USD   
2      AI00003                AI Specialist      152626             USD   
3      AI00004                 NLP Engineer       80215             USD   
4      AI00005                AI Consultant       54624             EUR   
...        ...                          ...         ...             ...   
14995  AI14996            Robotics Engineer       38604             USD   
14996  AI14997  Machine Learning Researcher       57811             GBP   
14997  AI14998                 NLP Engineer      189490             USD   
14998  AI14999                   Head of AI       79461             EUR   
14999  AI15000     Computer Vision Engineer       56481             USD   

      experience_level employment_type company_location company_size  \
0                   SE              CT            China            M   
1                   EN              CT           Canada            M   
2                   MI              FL      Switzerland            L   
3                   SE              FL            India            M   
4                   EN              PT           France            S   
...                ...             ...              ...          ...   
14995               EN              FL          Finland            S   
14996               EN              CT   United Kingdom            M   
14997               EX              CT      South Korea            L   
14998               EN              FT      Netherlands            M   
14999               MI              PT          Austria            S   

      employee_residence  remote_ratio  \
0                  China            50   
1                Ireland           100   
2            South Korea             0   
3                  India            50   
4              Singapore           100   
...                  ...           ...   
14995            Finland            50   
14996     United Kingdom             0   
14997        South Korea            50   
14998        Netherlands             0   
14999            Austria            50   

                                       required_skills education_required  \
0             Tableau, PyTorch, Kubernetes, Linux, NLP           Bachelor   
1      Deep Learning, AWS, Mathematics, Python, Docker             Master   
2         Kubernetes, Deep Learning, Java, Hadoop, NLP          Associate   
3                            Scala, SQL, Linux, Python                PhD   
4                         MLOps, Java, Tableau, Python             Master   
...                                                ...                ...   
14995                          Java, Kubernetes, Azure           Bachelor   
14996          Mathematics, Docker, SQL, Deep Learning             Master   
14997                                Scala, Spark, NLP          Associate   
14998        Java, Computer Vision, Python, TensorFlow                PhD   
14999    Scala, Azure, Deep Learning, GCP, Mathematics                PhD   

       years_experience       industry posting_date application_deadline  \
0                     9     Automotive   2024-10-18           2024-11-07   
1                     1          Media   2024-11-20           2025-01-11   
2                     2      Education   2025-03-18           2025-04-07   
3                     7     Consulting   2024-12-23           2025-02-24   
4                     0          Media   2025-04-15           2025-06-23   
...                 ...            ...          ...                  ...   
14995                 1         Energy   2025-02-06           2025-03-25   
14996                 0     Government   2024-10-16           2024-10-30   
14997                17  Manufacturing   2024-03-19           2024-05-02   
14998                 1    Real Estate   2024-03-22 

In [71]:
df['salary_currency']=df['salary_currency'] .astype('category')

In [72]:
df["job_title"] = df["job_title"].str.strip().str.title()
job_title


'Data Scientist'

In [73]:
df.job_title[0]

'Ai Research Scientist'

In [74]:
from datasets import load_dataset
df=load_dataset('lukebarousse/data_jobs')
df=df['train'].to_pandas()

c:\Users\mypc\Desktop\DataScience\.venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [75]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 785741 entries, 0 to 785740
Data columns (total 17 columns):
 #   Column                 Non-Null Count   Dtype  
---  ------                 --------------   -----  
 0   job_title_short        785741 non-null  object 
 1   job_title              785740 non-null  object 
 2   job_location           784696 non-null  object 
 3   job_via                785733 non-null  object 
 4   job_schedule_type      773074 non-null  object 
 5   job_work_from_home     785741 non-null  bool   
 6   search_location        785741 non-null  object 
 7   job_posted_date        785741 non-null  object 
 8   job_no_degree_mention  785741 non-null  bool   
 9   job_health_insurance   785741 non-null  bool   
 10  job_country            785692 non-null  object 
 11  salary_rate            33067 non-null   object 
 12  salary_year_avg        22003 non-null   float64
 13  salary_hour_avg        10662 non-null   float64
 14  company_name           785723 non-nu

In [76]:
df.iloc[20:30, 1:4]

job_title  \
20                                     Data Scientist   
21  Stage - data scientist – génération ia de donn...   
22      Data Engineer / Développeur·euse Big Data F/H   
23    PhD position in computer science (NLP, finance)   
24                      Data Scientist (DataLab Team)   
25                  Senior Officer, Data Analyst, GTO   
26                                      Data Engineer   
27  Principal Data Engineer (Lead), Knowledge Grap...   
28                                CRM Data Specialist   
29                                     Data Scientist   

                               job_location              job_via  
20                        Zaventem, Belgium   via BeBee Belgique  
21               Asnières-sur-Seine, France         via Jobijoba  
22                           Nantes, France         via LinkedIn  
23                                   Russia            via hh.ru  
24                                 Anywhere         via LinkedIn  
25                                Singapore  via BeBee Singapore  
26                            United States         via LinkedIn  
27                        San Francisco, CA         via LinkedIn  
28  San José Province, San José, Costa Rica      via Ai-Jobs.net  
29                 Pune, Maharashtra, India           via Exusia

In [77]:
df['job_posted_date']=pd.to_datetime(df['job_posted_date'])


In [78]:
df.describe()

job_posted_date  salary_year_avg  salary_hour_avg
count                         785741     22003.000000     10662.000000
mean   2023-06-25 16:02:11.860248576    123286.274072        47.016598
min              2023-01-01 00:00:04     15000.000000         8.000000
25%              2023-03-20 10:05:48     90000.000000        27.500000
50%              2023-06-29 06:11:38    115000.000000        45.980000
75%              2023-09-27 01:01:16    150000.000000        61.159996
max              2023-12-31 23:59:58    960000.000000       391.000000
std                              NaN     48312.449482        21.890738

In [79]:
df['job_title_short'].value_counts()

job_title_short
Data Analyst                 196075
Data Engineer                186241
Data Scientist               172286
Business Analyst              49063
Software Engineer             44929
Senior Data Engineer          44563
Senior Data Scientist         36957
Senior Data Analyst           29216
Machine Learning Engineer     14080
Cloud Engineer                12331
Name: count, dtype: int64

In [89]:
df.groupby(['job_title_short','job_country'])['salary_year_avg'].median()

job_title_short    job_country
Business Analyst   Afghanistan        NaN
                   Albania            NaN
                   Algeria            NaN
                   Angola             NaN
                   Argentina      71100.0
                                   ...   
Software Engineer  Venezuela          NaN
                   Vietnam        53600.0
                   Yemen              NaN
                   Zambia             NaN
                   Zimbabwe           NaN
Name: salary_year_avg, Length: 1387, dtype: float64

In [91]:
df.groupby('job_title_short')[['salary_year_avg','salary_hour_avg']].median()

salary_year_avg  salary_hour_avg
job_title_short                                            
Business Analyst                   85000.0        40.362499
Cloud Engineer                     90000.0        40.000000
Data Analyst                       90000.0        32.615002
Data Engineer                     125000.0        58.500000
Data Scientist                    127500.0        47.500000
Machine Learning Engineer         106415.0        47.535000
Senior Data Analyst               111175.0        47.500000
Senior Data Engineer              147500.0        61.500000
Senior Data Scientist             155500.0        47.620003
Software Engineer                  99150.0        47.560001

In [93]:
df.groupby('job_title_short')['salary_year_avg'].agg(['mean','median','min','max']).sort_values(by='median', ascending=False)

mean    median      min       max
job_title_short                                                      
Senior Data Scientist      154206.292996  155500.0  45000.0  890000.0
Senior Data Engineer       145840.611624  147500.0  35000.0  425000.0
Data Scientist             135988.837171  127500.0  27000.0  960000.0
Data Engineer              130125.604250  125000.0  15000.0  525000.0
Senior Data Analyst        113911.363665  111175.0  30000.0  425000.0
Machine Learning Engineer  126774.315972  106415.0  30000.0  325000.0
Software Engineer          113393.760054   99150.0  28000.0  375000.0
Cloud Engineer             111268.453846   90000.0  42000.0  280000.0
Data Analyst                93841.907854   90000.0  25000.0  650000.0
Business Analyst            91082.612833   85000.0  16500.0  387460.0